### ISSUE TITLE
Task run failed with exception ValueError('Invalid format string') 

### ISSUE THREAD

**Issue by kdjani** [PrefectHQ/ControlFlow#196]
I am running into this error with first task from the tutorial. 

**Environment/System**
I am on Windows 11 pro
pip_list is installed 
using an anaconda prompt to run the script in a virtual environment

**Here is my task**
```
import controlflow as cf
hello_task = cf.Task("say hello")
hello_task.run()

```
**Here is the error**
[pip_list.txt](https://github.com/user-attachments/files/16057152/pip_list.txt)

```

00:04:20.859 | ERROR   | Task run 'Run LLM' - Task run failed with exception ValueError('Invalid format string') - Retries are exhausted
00:04:20.957 | ERROR   | Task run 'Run LLM' - Finished in state Failed('Task run encountered an exception ValueError: Invalid format string')
00:04:20.967 | ERROR   | Flow run 'devious-whale' - Encountered exception during execution: Invalid format string
Traceback (most recent call last):
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\flow_engine.py", line 571, in run_context
    yield self
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\flow_engine.py", line 662, in run_generator_flow_sync
    yield gen_result
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\controlflow\flows\flow.py", line 95, in create_context
    yield self
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\controlflow\controllers\controller.py", line 340, in run
    new_messages = self.run_once()
                   ^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\tasks.py", line 826, in __call__
    return run_task(
           ^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\task_engine.py", line 862, in run_task
    return run_task_sync(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\task_engine.py", line 675, in run_task_sync
    return engine.state if return_type == "state" else engine.result()
                                                       ^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\task_engine.py", line 307, in result
    _result = self.state.result(raise_on_failure=raise_on_failure, fetch=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\client\schemas\objects.py", line 262, in result
    return get_state_result(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\states.py", line 68, in get_state_result
    return _get_state_result(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\utilities\asyncutils.py", line 389, in coroutine_wrapper
    return run_coro_as_sync(ctx_call())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\utilities\asyncutils.py", line 248, in run_coro_as_sync
    return call.result()
           ^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 312, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 173, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 383, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\utilities\asyncutils.py", line 231, in coroutine_wrapper
    return await task
           ^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\utilities\asyncutils.py", line 379, in ctx_call
    result = await async_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\states.py", line 127, in _get_state_result
    raise await get_state_exception(state)
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\task_engine.py", line 619, in run_context
    yield self
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\task_engine.py", line 673, in run_task_sync
    engine.call_task_fn(txn)
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\task_engine.py", line 647, in call_task_fn
    result = call_with_parameters(self.task.fn, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\utilities\callables.py", line 208, in call_with_parameters
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\controlflow\controllers\controller.py", line 291, in run_once
    for _ in response_gen:
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\controlflow\llm\completions.py", line 307, in _handle_events
    for event in generator:
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\controlflow\llm\completions.py", line 167, in _completion_generator
    yield from handle_delta_events(
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\controlflow\llm\completions.py", line 78, in handle_delta_events
    yield CompletionEvent(
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\controlflow\llm\completions.py", line 310, in _handle_events
    handler.on_event(event)
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\controlflow\llm\handlers.py", line 25, in on_event
    method(**event.payload)
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\controlflow\handlers\print_handler.py", line 78, in on_tool_call_delta
    self.update_live()
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\controlflow\handlers\print_handler.py", line 60, in update_live
    content.append(format_message(message, tool_results=tool_results))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\controlflow\handlers\print_handler.py", line 155, in format_message
    subtitle=f"[italic]{format_timestamp(message.timestamp)}[/]",
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\controlflow\handlers\print_handler.py", line 107, in format_timestamp
    return local_timestamp.strftime("%l:%M:%S %p")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid format string
00:04:21.135 | ERROR   | Flow run 'devious-whale' - Finished in state Failed('Flow run encountered an exception: ValueError: Invalid format string')
00:04:21.140 | ERROR   | Task run 'Run LLM Controller' - Task run failed with exception ValueError('Invalid format string') - Retries are exhausted
00:04:21.231 | ERROR   | Task run 'Run LLM Controller' - Finished in state Failed('Task run encountered an exception ValueError: Invalid format string')
00:04:21.237 | ERROR   | Task run 'Run Task a0cf6 ("say hello")' - Task run failed with exception ValueError('Invalid format string') - Retries are exhausted
00:04:21.376 | ERROR   | Task run 'Run Task a0cf6 ("say hello")' - Finished in state Failed('Task run encountered an exception ValueError: Invalid format string')
Traceback (most recent call last):
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\firsttask.py", line 5, in <module>
    hello_task.run()
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\tasks.py", line 826, in __call__
    return run_task(
           ^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\task_engine.py", line 862, in run_task
    return run_task_sync(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\task_engine.py", line 675, in run_task_sync
    return engine.state if return_type == "state" else engine.result()
                                                       ^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\task_engine.py", line 307, in result
    _result = self.state.result(raise_on_failure=raise_on_failure, fetch=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\client\schemas\objects.py", line 262, in result
    return get_state_result(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\states.py", line 68, in get_state_result
    return _get_state_result(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\utilities\asyncutils.py", line 389, in coroutine_wrapper
    return run_coro_as_sync(ctx_call())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\utilities\asyncutils.py", line 248, in run_coro_as_sync
    return call.result()
           ^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 312, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 182, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 383, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\utilities\asyncutils.py", line 231, in coroutine_wrapper
    return await task
           ^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\utilities\asyncutils.py", line 379, in ctx_call
    result = await async_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\states.py", line 127, in _get_state_result
    raise await get_state_exception(state)
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\task_engine.py", line 619, in run_context
    yield self
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\task_engine.py", line 673, in run_task_sync
    engine.call_task_fn(txn)
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\task_engine.py", line 647, in call_task_fn
    result = call_with_parameters(self.task.fn, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\utilities\callables.py", line 208, in call_with_parameters
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\controlflow\tasks\task.py", line 354, in run
    controller.run()
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\tasks.py", line 826, in __call__
    return run_task(
           ^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\task_engine.py", line 862, in run_task
    return run_task_sync(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\task_engine.py", line 675, in run_task_sync
    return engine.state if return_type == "state" else engine.result()
                                                       ^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\task_engine.py", line 307, in result
    _result = self.state.result(raise_on_failure=raise_on_failure, fetch=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\client\schemas\objects.py", line 262, in result
    return get_state_result(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\states.py", line 68, in get_state_result
    return _get_state_result(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\utilities\asyncutils.py", line 389, in coroutine_wrapper
    return run_coro_as_sync(ctx_call())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\utilities\asyncutils.py", line 248, in run_coro_as_sync
    return call.result()
           ^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 312, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 182, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 383, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\utilities\asyncutils.py", line 231, in coroutine_wrapper
    return await task
           ^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\utilities\asyncutils.py", line 379, in ctx_call
    result = await async_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\states.py", line 127, in _get_state_result
    raise await get_state_exception(state)
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\task_engine.py", line 619, in run_context
    yield self
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\task_engine.py", line 673, in run_task_sync
    engine.call_task_fn(txn)
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\task_engine.py", line 647, in call_task_fn
    result = call_with_parameters(self.task.fn, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\utilities\callables.py", line 208, in call_with_parameters
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\controlflow\controllers\controller.py", line 340, in run
    new_messages = self.run_once()
                   ^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\tasks.py", line 826, in __call__
    return run_task(
           ^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\task_engine.py", line 862, in run_task
    return run_task_sync(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\task_engine.py", line 675, in run_task_sync
    return engine.state if return_type == "state" else engine.result()
                                                       ^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\task_engine.py", line 307, in result
    _result = self.state.result(raise_on_failure=raise_on_failure, fetch=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\client\schemas\objects.py", line 262, in result
    return get_state_result(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\states.py", line 68, in get_state_result
    return _get_state_result(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\utilities\asyncutils.py", line 389, in coroutine_wrapper
    return run_coro_as_sync(ctx_call())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\utilities\asyncutils.py", line 248, in run_coro_as_sync
    return call.result()
           ^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 312, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 173, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 383, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\utilities\asyncutils.py", line 231, in coroutine_wrapper
    return await task
           ^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\utilities\asyncutils.py", line 379, in ctx_call
    result = await async_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\states.py", line 127, in _get_state_result
    raise await get_state_exception(state)
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\task_engine.py", line 619, in run_context
    yield self
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\task_engine.py", line 673, in run_task_sync
    engine.call_task_fn(txn)
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\task_engine.py", line 647, in call_task_fn
    result = call_with_parameters(self.task.fn, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\prefect\utilities\callables.py", line 208, in call_with_parameters
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\controlflow\controllers\controller.py", line 291, in run_once
    for _ in response_gen:
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\controlflow\llm\completions.py", line 307, in _handle_events
    for event in generator:
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\controlflow\llm\completions.py", line 167, in _completion_generator
    yield from handle_delta_events(
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\controlflow\llm\completions.py", line 78, in handle_delta_events
    yield CompletionEvent(
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\controlflow\llm\completions.py", line 310, in _handle_events
    handler.on_event(event)
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\controlflow\llm\handlers.py", line 25, in on_event
    method(**event.payload)
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\controlflow\handlers\print_handler.py", line 78, in on_tool_call_delta
    self.update_live()
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\controlflow\handlers\print_handler.py", line 60, in update_live
    content.append(format_message(message, tool_results=tool_results))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\controlflow\handlers\print_handler.py", line 155, in format_message
    subtitle=f"[italic]{format_timestamp(message.timestamp)}[/]",
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\src\cagi\prefect\controlflow\myenv\Lib\site-packages\controlflow\handlers\print_handler.py", line 107, in format_timestamp
    return local_timestamp.strftime("%l:%M:%S %p")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid format string
```

**Comment by jlowin** [comment]
0.8.2 is out and includes #193
