### ISSUE TITLE
ControlFlow Dosent Work on Windows

### ISSUE THREAD

**Issue by kingabzpro** [PrefectHQ/ControlFlow#315]
### Description

I ran the sample code from documentation and I am getting an error that I cannot resolve. 

```
 File "C:\Repository\Hugging Face\Water-Quality-Classifier\test.py", line 17, in <module>                            
    classifications = cf.run(
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\controlflow\run.py", line 110, in run
    results = run_tasks(
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\tasks.py", line 997, in __call__
    return run_task(
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1491, in run_task
    return run_task_sync(**kwargs)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1298, in run_task_sync    
    with engine.start(task_run_id=task_run_id, dependencies=dependencies):
  File "C:\Users\abida\anaconda3\envs\py310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 712, in start
    with self.initialize_run(task_run_id=task_run_id, dependencies=dependencies):
  File "C:\Users\abida\anaconda3\envs\py310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 636, in initialize_run    
    with SyncClientContext.get_or_create() as client_ctx:
  File "C:\Users\abida\anaconda3\envs\py310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\context.py", line 231, in get_or_create
    with SyncClientContext() as ctx:
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\context.py", line 204, in __init__
    client=get_client(sync_client=True, httpx_settings=httpx_settings),
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\client\orchestration.py", line 218, in get_client
    server.start()
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\server\api\server.py", line 775, in start       
    self.server_process = self._run_uvicorn_command()
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\server\api\server.py", line 822, in _run_uvicorn_command
    return subprocess.Popen(
  File "C:\Users\abida\anaconda3\envs\py310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\abida\anaconda3\envs\py310\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

### Example Code

```Python
import controlflow as cf

tweets = [
    "Negativity spreads too easily here. #sigh",
    "Sometimes venting is necessary. #HateTherapy",
    "Love fills the air today! 💖 #Blessed",
    "Thankful for all my Twitter friends! 🌟",
]

# Create a specialized agent
classifier = cf.Agent(
    name="Tweet Classifier",
    model="openai/gpt-4o-mini",
    instructions="You are an expert at quickly classifying tweets.",
)
# Set up a ControlFlow task to classify tweets
classifications = cf.run(
    "Classify the tweets",
    result_type=["hate", "love"],
    agents=[classifier],
    context=dict(tweets=tweets),
)

print(classifications)
```

### Version Information

```Text
ControlFlow version: 0.9.3
       Prefect version: 3.0.2
LangChain Core version: 0.3.1
        Python version: 3.10.14
              Platform: Windows-10-10.0.22631-SP0
                  Path: C:\Users\abida\anaconda3\envs\py310\Lib
```

**Comment by kingabzpro** [comment]
@jlowin help me out. I thought I will have smooth journey but I cannot even pass the first step of trying out control flow.

**Comment by kingabzpro** [comment]
The code didn't ran. But starting the server resolved the issue. I didn't even have to set the environment variable for perfect URL

**Comment by kingabzpro** [comment]
The prefect code ran with the server but controlflow code is still not working.

**Comment by jlowin** [comment]
The code is also failing for me with gpt-4o-mini, but not gpt-4o. I'm not sure why - I will open a separate issue to track it. Sometimes mini tries to do odd things, so we give it slightly different instructions as part of the compilation.

**Comment by kingabzpro** [comment]
@jlowin I have resolved the subprocess issue with : `PREFECT_API_URL="http://127.0.0.1:4200/api"`

But I got another issues that is same in Colab and Windows:

```
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\controlflow\agents\agent.py", line 308, in _run_model
    {response.json(indent=2)}
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\pydantic\main.py", line 1119, in json       
    raise TypeError('`dumps_kwargs` keyword arguments are no longer supported.')
TypeError: `dumps_kwargs` keyword arguments are no longer supported.
```

**Comment by kingabzpro** [comment]
I tried it with GPT-4o and I got this:

```
─ Agent: Tweet Classifier ────────────────────────────────────────────────────────────────────────╮      
│                                                                                                  │      
│  I will classify the tweets as either "hate" or "love". Here are the tweets:                     │      
│                                                                                                  │      
│   1 "Negativity spreads too easily here. #sigh"                                                  │      
│   2 "Sometimes venting is necessary. #HateTherapy"                                               │      
│   3 "Love fills the air today! 💖 #Blessed"                                                      │      
│   4 "Thankful for all my Twitter friends! 🌟"                                                    │      
│                                                                                                  │      
                                                   ...                                                    
16:25:35.347 | ERROR   | Task run 'Call LLM' - Task run failed with exception: TypeError('`dumps_kwargs` keyword arguments are no longer supported.') - Retries are exhausted
Traceback (most recent call last):
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 752, in run_context
    yield self
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1371, in run_generator_task_sync
    gen_result = next(gen)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\controlflow\agents\agent.py", line 308, in _run_model
    {response.json(indent=2)}
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\pydantic\main.py", line 1119, in json       
    raise TypeError('`dumps_kwargs` keyword arguments are no longer supported.')
TypeError: `dumps_kwargs` keyword arguments are no longer supported.
16:25:35.362 | ERROR   | Task run 'Call LLM' - Finished in state Failed('Task run encountered an exception TypeError: `dumps_kwargs` keyword arguments are no longer supported.')
16:25:35.364 | ERROR   | Task run 'Agent turn: Tweet Classifier' - Task run failed with exception: TypeError('`dumps_kwargs` keyword arguments are no longer supported.') - Retries are exhausted
Traceback (most recent call last):
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 752, in run_context
    yield self
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1302, in run_task_sync
    engine.call_task_fn(txn)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 775, in call_task_fn
    result = call_with_parameters(self.task.fn, parameters)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\utilities\callables.py", line 206, in call_with_parameters
    return fn(*args, **kwargs)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\controlflow\orchestration\orchestrator.py", line 321, in run_agent_turn
    for event in self.agent._run_model(messages=messages, tools=tools):
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1386, in run_generator_task_sync
    return engine.result()
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 455, in result
    raise self._raised
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 752, in run_context
    yield self
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1371, in run_generator_task_sync
╭─ Agent: Tweet Classifier ────────────────────────────────────────────────────────────────────────╮      
│                                                                                                  │      
│  I will classify the tweets as either "hate" or "love". Here are the tweets:                     │      
│                                                                                                  │      
│   1 "Negativity spreads too easily here. #sigh"                                                  │      
│   2 "Sometimes venting is necessary. #HateTherapy"                                               │      
│   3 "Love fills the air today! 💖 #Blessed"                                                      │      
│   4 "Thankful for all my Twitter friends! 🌟"                                                    │      
│                                                                                                  │      
│  Let's classify them:                                                                            │      
│                                                                                                  │      
│   1 Hate                                                                                         │      
│   2 Hate                                                                                         │      
│   3 Love                                                                                         │      
│   4 Love                                                                                         │      
│                                                                                                  │      
│  Given the context, the overall sentiment of the tweets falls under "love" since the majority    │      
│  express positive feelings and gratitude.                                                        │      
│                                                                                                  │      
│  I will now mark the task as successful with the result "love".                                  │      
│                                                                                                  │      
│                                                                                                  │      
│  ⠙ Tool call: "mark_task_1cbddcef_successful"                                                    │      
│                                                                                                  │      
│    Tool args: {'result': 1}                                                                      │      
│                                                                                                  │      
╰────────────────────────────────────────────────────────────────────────────────────  4:25:35 PM ─╯      
16:25:35.376 | ERROR   | Task run 'Orchestrator.run()' - Task run failed with exception: TypeError('`dumps_kwargs` keyword arguments are no longer supported.') - Retries are exhausted
Traceback (most recent call last):
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 752, in run_context
    yield self
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1302, in run_task_sync
    engine.call_task_fn(txn)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 775, in call_task_fn
    result = call_with_parameters(self.task.fn, parameters)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\utilities\callables.py", line 206, in call_with_parameters
    return fn(*args, **kwargs)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\controlflow\orchestration\orchestrator.py", line 169, in run
    call_count += self.run_agent_turn(max_llm_calls - call_count)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\tasks.py", line 997, in __call__    
    return run_task(
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1491, in run_task
    return run_task_sync(**kwargs)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1304, in run_task_sync
    return engine.state if return_type == "state" else engine.result()
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 455, in result
    raise self._raised
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 752, in run_context
    yield self
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1302, in run_task_sync
    engine.call_task_fn(txn)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 775, in call_task_fn
    result = call_with_parameters(self.task.fn, parameters)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\utilities\callables.py", line 206, in call_with_parameters
    return fn(*args, **kwargs)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\controlflow\orchestration\orchestrator.py", line 321, in run_agent_turn
    for event in self.agent._run_model(messages=messages, tools=tools):
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1386, in run_generator_task_sync
    return engine.result()
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 455, in result
    raise self._raised
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 752, in run_context
    yield self
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1371, in run_generator_task_sync
    gen_result = next(gen)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\controlflow\agents\agent.py", line 308, in _run_model
    {response.json(indent=2)}
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\pydantic\main.py", line 1119, in json       
    raise TypeError('`dumps_kwargs` keyword arguments are no longer supported.')
TypeError: `dumps_kwargs` keyword arguments are no longer supported.
16:25:35.387 | ERROR   | Task run 'Orchestrator.run()' - Finished in state Failed('Task run encountered an exception TypeError: `dumps_kwargs` keyword arguments are no longer supported.')
16:25:35.388 | ERROR   | Task run 'Run task: Task #1cbddcef ("Classify the tweets")' - Task run failed with exception: TypeError('`dumps_kwargs` keyword arguments are no longer supported.') - Retries are exhausted
Traceback (most recent call last):
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 752, in run_context
    yield self
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1302, in run_task_sync
    engine.call_task_fn(txn)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 775, in call_task_fn
    result = call_with_parameters(self.task.fn, parameters)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\utilities\callables.py", line 206, in call_with_parameters
    return fn(*args, **kwargs)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\controlflow\run.py", line 45, in run_tasks  
    orchestrator.run(
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\tasks.py", line 997, in __call__    
    return run_task(
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1491, in run_task
    return run_task_sync(**kwargs)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1304, in run_task_sync
    return engine.state if return_type == "state" else engine.result()
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 455, in result
    raise self._raised
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 752, in run_context
    yield self
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1302, in run_task_sync
    engine.call_task_fn(txn)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 775, in call_task_fn
    result = call_with_parameters(self.task.fn, parameters)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\utilities\callables.py", line 206, in call_with_parameters
    return fn(*args, **kwargs)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\controlflow\orchestration\orchestrator.py", line 169, in run
    call_count += self.run_agent_turn(max_llm_calls - call_count)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\tasks.py", line 997, in __call__    
    return run_task(
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1491, in run_task
    return run_task_sync(**kwargs)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1304, in run_task_sync
    return engine.state if return_type == "state" else engine.result()
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 455, in result
    raise self._raised
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 752, in run_context
    yield self
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1302, in run_task_sync
    engine.call_task_fn(txn)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 775, in call_task_fn
    result = call_with_parameters(self.task.fn, parameters)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\utilities\callables.py", line 206, in call_with_parameters
    return fn(*args, **kwargs)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\controlflow\orchestration\orchestrator.py", line 321, in run_agent_turn
    for event in self.agent._run_model(messages=messages, tools=tools):
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1386, in run_generator_task_sync
    return engine.result()
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 455, in result
    raise self._raised
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 752, in run_context
    yield self
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1371, in run_generator_task_sync
    gen_result = next(gen)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\controlflow\agents\agent.py", line 308, in _run_model
    {response.json(indent=2)}
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\pydantic\main.py", line 1119, in json       
    raise TypeError('`dumps_kwargs` keyword arguments are no longer supported.')
TypeError: `dumps_kwargs` keyword arguments are no longer supported.
16:25:35.398 | ERROR   | Task run 'Run task: Task #1cbddcef ("Classify the tweets")' - Finished in state Failed('Task run encountered an exception TypeError: `dumps_kwargs` keyword arguments are no longer supported.')
Traceback (most recent call last):
  File "C:\Repository\Hugging Face\Water-Quality-Classifier\test.py", line 17, in <module>
    classifications = cf.run(
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\controlflow\run.py", line 110, in run       
    results = run_tasks(
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\tasks.py", line 997, in __call__    
    return run_task(
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1491, in run_task
    return run_task_sync(**kwargs)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1304, in run_task_sync
    return engine.state if return_type == "state" else engine.result()
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 455, in result
    raise self._raised
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 752, in run_context
    yield self
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1302, in run_task_sync
    engine.call_task_fn(txn)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 775, in call_task_fn
    result = call_with_parameters(self.task.fn, parameters)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\utilities\callables.py", line 206, in call_with_parameters
    return fn(*args, **kwargs)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\controlflow\run.py", line 45, in run_tasks  
    orchestrator.run(
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\tasks.py", line 997, in __call__    
    return run_task(
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1491, in run_task
    return run_task_sync(**kwargs)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1304, in run_task_sync
    return engine.state if return_type == "state" else engine.result()
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 455, in result
    raise self._raised
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 752, in run_context
    yield self
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1302, in run_task_sync
    engine.call_task_fn(txn)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 775, in call_task_fn
    result = call_with_parameters(self.task.fn, parameters)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\utilities\callables.py", line 206, in call_with_parameters
    return fn(*args, **kwargs)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\controlflow\orchestration\orchestrator.py", line 169, in run
    call_count += self.run_agent_turn(max_llm_calls - call_count)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\tasks.py", line 997, in __call__    
    return run_task(
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1491, in run_task
    return run_task_sync(**kwargs)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1304, in run_task_sync
    return engine.state if return_type == "state" else engine.result()
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 455, in result
    raise self._raised
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 752, in run_context
    yield self
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1302, in run_task_sync
    engine.call_task_fn(txn)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 775, in call_task_fn
    result = call_with_parameters(self.task.fn, parameters)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\utilities\callables.py", line 206, in call_with_parameters
    return fn(*args, **kwargs)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\controlflow\orchestration\orchestrator.py", line 321, in run_agent_turn
    for event in self.agent._run_model(messages=messages, tools=tools):
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1386, in run_generator_task_sync
    return engine.result()
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 455, in result
    raise self._raised
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 752, in run_context
    yield self
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\prefect\task_engine.py", line 1371, in run_generator_task_sync
    gen_result = next(gen)
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\controlflow\agents\agent.py", line 308, in _run_model
    {response.json(indent=2)}
  File "C:\Users\abida\anaconda3\envs\py310\lib\site-packages\pydantic\main.py", line 1119, in json       
    raise TypeError('`dumps_kwargs` keyword arguments are no longer supported.')
TypeError: `dumps_kwargs` keyword arguments are no longer supported.
```
